services:
  db:
    image: postgres:15
    container_name: learning_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: learning_api
    env_file:
      - .env
    volumes:
      - .:/app 
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080

volumes:
  postgres_data: