version: "3.9"

services:
  db:
    image: postgres:15
    container_name: learning_db
    env_file: 
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learning_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: learning_api
    env_file:
     - .env
    depends_on:
      - db
    environment:
      DATABASE_URL:  postgresql+asyncpg://postgres:password@db:5432/learning_db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

volumes:
  postgres_data:
