"""add beginner diagram

Revision ID: a3dc33b014f9
Revises: 5b6e761c2b6a
Create Date: 2026-05-08 18:17:53.223321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dc33b014f9'
down_revision: Union[str, Sequence[str], None] = '5b6e761c2b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('diagram_to_fill', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'diagram_to_fill')
    # ### end Alembic commands ###
