"""add hint taken to submission

Revision ID: b3fadb532b31
Revises: a3dc33b014f9
Create Date: 2026-05-24 12:21:20.705035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fadb532b31'
down_revision: Union[str, Sequence[str], None] = 'a3dc33b014f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_submissions', sa.Column('took_hint', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_submissions', 'took_hint')
    # ### end Alembic commands ###
