"""modify question schema

Revision ID: c3f389e54492
Revises: 1515534c4617
Create Date: 2026-04-17 13:03:44.752323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f389e54492'
down_revision: Union[str, Sequence[str], None] = '1515534c4617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_table('prompts')
    op.add_column('questions', sa.Column('task_description', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('starter_diagram', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('prompt', sa.Text(), nullable=False,server_default=""))
    op.drop_column('questions', 'mermaid_diagram')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['username'], unique=True)
    op.add_column('questions', sa.Column('mermaid_diagram', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'prompt')
    op.drop_column('questions', 'starter_diagram')
    op.drop_column('questions', 'task_description')
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prompt_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('prompts_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prompts_pkey'))
    )
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    # ### end Alembic commands ###
