"""update submissions

Revision ID: 21ee9f32d4c6
Revises: c3f389e54492
Create Date: 2026-04-29 11:00:03.796599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ee9f32d4c6'
down_revision: Union[str, Sequence[str], None] = 'c3f389e54492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_submissions', sa.Column('diagram_json', sa.JSON(), nullable=True))
    op.add_column('student_submissions', sa.Column('solution_type', sa.String(), nullable=True))
    op.add_column('student_submissions', sa.Column('solution_json', sa.JSON(), nullable=True))
    op.alter_column('student_submissions', 'solution_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_submissions', 'solution_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('student_submissions', 'solution_json')
    op.drop_column('student_submissions', 'solution_type')
    op.drop_column('student_submissions', 'diagram_json')
    # ### end Alembic commands ###
