"""add module xp

Revision ID: a1c23e4f1099
Revises: 294cac4ccda6
Create Date: 2026-03-09 08:01:33.298969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c23e4f1099'
down_revision: Union[str, Sequence[str], None] = '294cac4ccda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_question_progress', sa.Column('xp_earned', sa.Integer(), nullable=True))
    op.drop_column('student_question_progress', 'best_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_question_progress', sa.Column('best_grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('student_question_progress', 'xp_earned')
    # ### end Alembic commands ###
